# заметки по докеру для джавы:
# не пересобирает dockerfile при docker-compose up -d, в отличии от питона
# gradle выдает ошибку hibernate при запуске тестов, поэтому пока их пропускаем при сборке

services:

  nginx:
    container_name: nginx
    image: nginx:1.27.3
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./deployment/nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./deployment/certbot/conf:/etc/letsencrypt
      - ./deployment/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - backend

  certbot:
    container_name: certbot
    image: certbot/certbot:v3.0.0
    restart: unless-stopped
    volumes:
      - ./deployment/certbot/conf:/etc/letsencrypt
      - ./deployment/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


  backend:
    container_name: backend
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/MyknowledgeDB

  db:
    container_name: db
    image: postgres:17
    environment:
      - POSTGRES_DB=MyknowledgeDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ksflkOkas23fl9saflKdl349sLfsk1
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data: