-- liquibase formatted sql

-- changeset t1:1734503234836-1
CREATE TABLE "relationships" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "status" VARCHAR(255), "received_relationship_id" BIGINT, "requested_relationship_id" BIGINT, "date_create" TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT "relationships_pkey" PRIMARY KEY ("id"));

-- changeset t1:1734503234836-2
CREATE TABLE "user_role" ("user_id" BIGINT NOT NULL, "roles" VARCHAR(255));

-- changeset t1:1734503234836-3
CREATE TABLE "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "access" VARCHAR(255), "active" BOOLEAN NOT NULL, "avatar" VARCHAR(255), "date_joined" TIMESTAMP WITHOUT TIME ZONE, "date_last_enter" TIMESTAMP WITHOUT TIME ZONE, "email" VARCHAR(30), "information" VARCHAR(255), "name" VARCHAR(30), "password" VARCHAR(1000), "surname" VARCHAR(30), "username" VARCHAR(30), CONSTRAINT "users_pkey" PRIMARY KEY ("id"));

-- changeset t1:1734503234836-4
ALTER TABLE "users" ADD CONSTRAINT "uk6dotkott2kjsp8vw4d0m25fb7" UNIQUE ("email");

-- changeset t1:1734503234836-5
ALTER TABLE "users" ADD CONSTRAINT "ukr43af9ap4edm43mmtq01oddj6" UNIQUE ("username");

-- changeset t1:1734503234836-6
CREATE TABLE "books" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "author" VARCHAR(40), "date_end_read" date, "date_last_enter" TIMESTAMP WITHOUT TIME ZONE, "date_publish" date, "date_start_read" date, "grade" SMALLINT NOT NULL, "language" VARCHAR(255), "number_of_pages" INTEGER NOT NULL, "photo" VARCHAR(255), "purpose_read" VARCHAR(255), "title" VARCHAR(30), "user_id" BIGINT, CONSTRAINT "books_pkey" PRIMARY KEY ("id"));

-- changeset t1:1734503234836-7
ALTER TABLE "books" ADD CONSTRAINT "fkcykkh3hxh89ammmwch0gw5o1s" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset t1:1734503234836-8
ALTER TABLE "relationships" ADD CONSTRAINT "fkflgr6hcr3yh7fgar4selfxl4" FOREIGN KEY ("received_relationship_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset t1:1734503234836-9
ALTER TABLE "user_role" ADD CONSTRAINT "fkj345gk1bovqvfame88rcx7yyx" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset t1:1734503234836-10
ALTER TABLE "relationships" ADD CONSTRAINT "fkkexwxi9jlet3d42nbbb1hiovl" FOREIGN KEY ("requested_relationship_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

